export const TICKERS = [
  { symbol: 'AL30',  name: 'Bono Argentina 2030',    type: 'bond' },
  { symbol: 'AL35',  name: 'Bono Argentina 2035',    type: 'bond' },
  { symbol: 'AL41',  name: 'Bono Argentina 2041',    type: 'bond' },
  { symbol: 'GGAL',  name: 'Grupo Financiero Galicia', type: 'arg' },
  { symbol: 'LOMA',  name: 'Loma Negra',              type: 'arg' },
  { symbol: 'PAMP',  name: 'Pampa Energía',           type: 'arg' },
  { symbol: 'SUPV',  name: 'Banco Supervielle',       type: 'arg' },
  { symbol: 'VIST',  name: 'Vista Energy',            type: 'arg' },
  { symbol: 'MELI',  name: 'MercadoLibre',            type: 'latam' },
  { symbol: 'TEN',   name: 'Tenaris',                 type: 'latam' },
  { symbol: 'YPFD',  name: 'YPF',                     type: 'arg' },
  { symbol: 'KO',    name: 'Coca-Cola',               type: 'us' },
  { symbol: 'MCD',   name: 'McDonald\'s',             type: 'us' },
  { symbol: 'T',     name: 'AT&T',                    type: 'us' },
  { symbol: 'WMT',   name: 'Walmart',                 type: 'us' },
  { symbol: 'DIS',   name: 'Walt Disney',             type: 'us' },
  { symbol: 'PG',    name: 'Procter & Gamble',        type: 'us' },
  { symbol: 'PDD',   name: 'PDD Holdings',            type: 'us' },
  { symbol: 'AAPL',  name: 'Apple',                   type: 'tech' },
  { symbol: 'MSFT',  name: 'Microsoft',               type: 'tech' },
  { symbol: 'GOOGL', name: 'Alphabet',                type: 'tech' },
  { symbol: 'AMZN',  name: 'Amazon',                  type: 'tech' },
  { symbol: 'META',  name: 'Meta Platforms',          type: 'tech' },
  { symbol: 'NVDA',  name: 'NVIDIA',                  type: 'tech' },
  { symbol: 'TSM',   name: 'TSMC',                    type: 'tech' },
  { symbol: 'AMD',   name: 'AMD',                     type: 'tech' },
  { symbol: 'AVGO',  name: 'Broadcom',                type: 'tech' },
  { symbol: 'ORCL',  name: 'Oracle',                  type: 'tech' },
  { symbol: 'CRM',   name: 'Salesforce',              type: 'tech' },
  { symbol: 'PANW',  name: 'Palo Alto Networks',      type: 'tech' },
  { symbol: 'SNOW',  name: 'Snowflake',               type: 'tech' },
  { symbol: 'TSLA',  name: 'Tesla',                   type: 'tech' },
  { symbol: 'NFLX',  name: 'Netflix',                 type: 'tech' },
  { symbol: 'PYPL',  name: 'PayPal',                  type: 'tech' },
  { symbol: 'BABA',  name: 'Alibaba',                 type: 'tech' },
]

export const TICKER_GROUPS = [
  { label: 'Argentine Bonds', types: ['bond'] },
  { label: 'Argentina', types: ['arg'] },
  { label: 'LatAm', types: ['latam'] },
  { label: 'US Blue Chip', types: ['us'] },
  { label: 'Tech', types: ['tech'] },
]
